---
apiVersion: v1
kind: Pod
metadata:
  name: crashloop-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["/bin/sh", "-c", "exit 1"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
