---
apiVersion: v1
kind: Pod
metadata:
  name: imagepullbackoff-nginx
spec:
  containers:
    - name: nginx
      image: nginx:nonexistent-tag
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"